### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by bushaaaa** [jamal0025/Discord-Success-Bot#1]
Hi, it gave me this while running:

online
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\nb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\nb\Discord-Success-Bot\main.py", line 37, in on_message
    image_url = message.attachments[0]['url']
TypeError: 'Attachment' object is not subscriptable

What did I do wrong?

**Comment by Stevie808** [comment]
Hey did you end up figuring this out?
